spring:
  application:
    name: sso
  datasource:
    url: jdbc:mysql://database-1-test.cdsga6wkuov5.ca-central-1.rds.amazonaws.com/opb
    username: admin
    password: ENC(w9Lzcwkcjdize4UC5Ieszo+fCSEMcaSIAF5AJV/SgSEm5TnfM7rR++C1KuQb9++fGRMtpMlbLuVAimx6tZRizQ==)
sso:
  secret:
    key: ENC(0aFqmqsTMmBTxJyGagODqLkkxL4ENwcaVMJvOFOQRz0vAHII8FML81o0dwjQL9WqtmuURGZ8XwANcIo+mXxsGl9jSr4OPX6t6OW8QvCrf7OEvqtksW3Md0uMv31VW+Z0)
server:
  servlet:
    context-path: /sso/api
